### ISSUE TITLE
Documentation: README.md Clarification and Wiki Correction

### ISSUE THREAD

**Issue by ReedClanton** [FlyingWolFox/Netscape-Bookmarks-File-Parser#7]
# README.md

This project's documentation is very good, however, I had a lot of trouble figuring out how to use the parser's methods. Eventually I found the line `The folder tree can be navigated using the "." notation.` and figured out what was meant by it. I think having a simple, short text block in the `README.md` demonstrating what is meant by that line would make it much more clear.

## Example

This may be too much.

```
from NetscapeBookmarksFileParser import *
from NetscapeBookmarksFileParser import parser

with open('bookmarks.html') as file:
    bookmarks = NetscapeBookmarksFile(file).parse()

bookmarks.bookmarks.items.<desiredContent>
``` 

# Wiki Changes

In [The BookmarkFolder class](https://github.com/FlyingWolFox/Netscape-Bookmarks-File-Parser/wiki/Code-Documentation#the-bookmarkfolder-class) section of the wiki lists `entries` as one of the available variables. This is not true.

**Comment by FlyingWolFox** [comment]
Hello @ReedClanton! Thank you for filling an issue. Sorry for the wait.

I fixed the wiki, the correct property is `shortcuts`, not `entries`, and added an quick example to the README.

Honestly, I don't understand nor remember what `The folder tree can be navigated using the "." notation.` meant, because you navigate the file using the `items`, `children` and `shortcuts` lists with `[]` (like `folder.items[0]`)

If there's more that I can do to improve the documentation, hit me up!
